name: AuthSvc

on:
  push:
    paths:
      - 'authsvc/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./authsvc
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Verify dependencies
      run: go mod verify
      shell: bash

    - name: Run go vet
      run: go vet ./...
      shell: bash

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
      shell: bash

    - name: Run staticcheck
      run: staticcheck ./...
      shell: bash

    # - name: Run tests
    #   run: go test ./...

    - name: Build
      run: go build -v ./...
      shell: bash
